# Generated by Django 5.0.7 on 2024-08-01 20:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sku", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Electronics", "Electronics"),
                            ("Home & Kitchen", "Home & Kitchen"),
                            ("Books", "Books"),
                            ("Beauty & Personal Care", "Beauty & Personal Care"),
                            ("Clothing", "Clothing"),
                            ("Sports & Outdoors", "Sports & Outdoors"),
                            ("Toys & Games", "Toys & Games"),
                        ],
                        max_length=50,
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("in", "In"), ("out", "Out")], max_length=15
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.products",
                    ),
                ),
            ],
        ),
    ]
