# Generated by Django 5.0.7 on 2024-08-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="stock",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
